### ISSUE TITLE
Requests permissions but never succeeds in getting access

### ISSUE THREAD

**Issue by apanagar** [vashpan/xcode-dev-cleaner#20] opened 2021-02-26 02:50 UTC
The app was working but now when I open it I get the following. I click the button, it beachballs for a little while, and then nothing happens.

I look under Security-> Privacy-> Files and Folders but didn't see this app listed

![image](https://user-images.githubusercontent.com/180389/109248230-4585d600-779a-11eb-885a-e22d3eab7d02.png)

Love the app, I use it a ton

**Comment by vashpan** [comment] 2021-03-21 21:10
Sorry for late answer... 

Do you still have an issue? I would love to debug it with you, as it seems you used it before and it lost the access after a while. I had reports of similar issues (mostly in some reviews on Mac App Store) but I never was able to track the issue down...

Could you reach me with logs (DevCleaner -> Show Log Files...)?

**Comment by tylerdigit** [comment] 2021-03-22 18:49
This just started happening to me. Logged on startup and when clicking the Give Access button:

❌ XcodeFiles: Cannot create because Xcode cache folders doesn't seem to exist or we don't have proper access to them!
⚠️ MainViewController: Cannot create XcodeFiles instance!

**Comment by vashpan** [comment] 2021-03-22 19:55
Hello

Thank you for your response

Hmm, ok so not much from logs... I have a few questions (they ma be silly):
- does folder ~/Library/Developer exists on your machine at all?
- maybe you changed your computer recently? or had a system restore?
- "Give Access" doesn't show a folder dialog at all?

BR
Konrad

**Comment by apanagar** [comment] 2021-03-22 20:02
> Sorry for late answer...
> 
> Do you still have an issue? I would love to debug it with you, as it seems you used it before and it lost the access after a while. I had reports of similar issues (mostly in some reviews on Mac App Store) but I never was able to track the issue down...
> 
> Could you reach me with logs (DevCleaner -> Show Log Files...)?

No prob, thanks for the reply. I don't have anything useful in the way of logs but if I encounter the issue again I'll be sure to respond to this issue or open a new issue with the logs. Didn't realize there were logs available!

**Comment by tylerdigit** [comment] 2021-03-23 13:55
> - does folder ~/Library/Developer exists on your machine at all? 

<img width="258" alt="image" src="https://user-images.githubusercontent.com/26227135/112156866-0726df80-8bbd-11eb-9a96-1169c091e8b2.png">


> - maybe you changed your computer recently? or had a system restore?

The only recent system change that I can think of is updating to Big Sur 11.2.3.


> - "Give Access" doesn't show a folder dialog at all?

Nope, just that log message.

**Comment by vashpan** [comment] 2021-03-23 15:37
Thanks, I'll try to reproduce it, or at least check what could cause that... Would you mind if I'll reach you with some debug build with more logging maybe as well?

BR
Konrad

**Comment by saroar** [comment] 2021-09-06 13:11
not fixed yet yes?

**Comment by vashpan** [comment] 2021-09-06 15:31
@saroar Do you have more info about it maybe? 🤔 I understand you also have this issue?

**Comment by saroar** [comment] 2021-09-06 15:38
sorry i don't mention it my Xcode version is Xcode 13 beta 5 may this reason

**Comment by vashpan** [comment] 2021-09-23 13:26
It shouldn't matter to be honest... I'm quite worried this is still not fixed :/ Waiting for more info...

**Comment by PreludeAndFugue** [comment] 2021-11-05 00:48
I deleted ~/Library/Developer/CoreSimulator. Pressing the "Give Access" button in DevCleaner does nothing. I restarted Xcode 13, configured a couple of simulators, built and run an app. Xcode has recreated the CoreSimulator folder. DevCleaner works again.

**Comment by vashpan** [comment] 2021-11-06 12:33
Hmmm, thanks for that info! Maybe it's related to the permissions or something 🤔

**Comment by phynet** [comment] 2022-01-16 15:13
Hi, I just have the same issue, but I think the problem is that it tries to open directly the Library/Developer path and doesn't recognize it (don't know why). What I did first was adding the app in the Security & Privacy settings (Full Disk access) and this neither work, at least with the prompt that appears at the begining of the app (to select files?) see image:
![image](https://user-images.githubusercontent.com/724536/149665741-4c8fb0fe-ba6c-4754-a886-4426965e8099.png)

Second step was to move manually the folder picker that appears in the app and it worked. I'm using Big Sur 11.6.1. Hope this helps somehow. I haven't checked the code prompt of the app, I should so I can learn haha. 

Thanks for the app I love it ;)

**Comment by vashpan** [comment] 2022-01-20 18:59
> Thanks for the app I love it ;)

😍


> Second step was to move manually the folder picker that appears in the app and it worked. I'm using Big Sur 11.6.1. Hope this helps somehow. I haven't checked the code prompt of the app, I should so I can learn haha.
> 

What do you mean by "move manually the folder picker" 🤔 To move a Developer path to DevCleaner folder pickup folder?

**Comment by phynet** [comment] 2022-02-03 14:37
Sorry for the delay.  When the selection of the folder path opens automatically it fails, it won't show the selection screen like in the image because I didn't have permissions. Then I just manually tried to select it, and it work. I don't have the opportunity to replicate it, since I switched Macs. But if it happens again I will come back to this thread and add the image. 
![Screenshot 2022-02-03 at 15 24 44](https://user-images.githubusercontent.com/724536/152361714-c8047dc3-14ed-461e-a6ed-219ff54a6738.png)

**Comment by vashpan** [comment] 2022-02-03 20:13
Thanks for your informations 👍 I'll be investigating this issue, as it's reported more and more often for some reason...

**Comment by vashpan** [comment] 2022-02-11 11:45
Hello guys, small update on this topic. I tried to reproduce this issue but unfortunately I couldn't. Seems to be quite specific to some edge case. From what I checked in the code and symptoms presented here, it could happen if access bookmark was created but for some case was invalid.

I've added some diagnostics and more logging for this case and maybe with future update, if this problem persists, we could get some more informations about this issue.

**Comment by vashpan** [comment] 2022-02-15 14:37
With recent updates to acquiring security scoped bookmarks, there's a chance this issue will be fixed in upcoming version. Please let me know if that won't happen. Thanks!

**Closed by vashpan** 2022-02-15 14:37 UTC
Labels: bug, question

**Comment by phynet** [comment] 2022-02-15 15:05
Thank you @vashpan . To me didn't happen again even reinstalling the app. Which is weird, but I will not complain 🦖  If happened again I will try to take screen captures. 👋

**Comment by MikaReesu** [comment] 2023-01-17 19:50
Hello, I have the same issue on Ventura 13.1.

Log : 
⚠️ URL+AcquireAccessFromSandbox: Didn't get folder from Open panel! Modal response: NSModalResponse(rawValue: 0)
⚠️ MainViewController: Cannot acquire "Developer" folder access! Showing access warning!

⚠️ URL+AcquireAccessFromSandbox: Didn't get folder from Open panel! Modal response: NSModalResponse(rawValue: -2)
⚠️ MainViewController: Cannot acquire "Developer" folder access! Showing access warning!
❕ Next reminder: Friday 17 February 2023 at 20:48:10 Central European Standard Time

I have the modal opening and it puts me in the developer folder afterward. But I have no idea about what to do after. 

<img width="667" alt="image" src="https://user-images.githubusercontent.com/79900890/212997823-c7b90744-7986-4ec1-964f-ecc3b0c5badb.png">

Hoping you will be able to help. 

Have a nice evening.

**Comment by vashpan** [comment] 2023-01-17 21:03
Hello

You should’ve just click „Open”, not selecting any other folder 🙂 Is there some error afterwards?

BR
Konrad

**Comment by MikaReesu** [comment] 2023-01-18 08:12
What do you do after you open? Any Folder I chose, will have a popup
showing saying "Can't access to Developer folder. Did you choose the right
folder."

What am I supposed to choose? This seems to not be very clear.

**Comment by MikaReesu** [comment] 2023-01-18 08:14
All is okay now apparently. It got the access now. Before I didn't have
access but now it looks okay. Thanks and have a good day.

**Comment by iamsergio** [comment] 2023-11-02 12:15
I got the "open dialog" at the 1st time, but it still shows the "Give Access" button, which doesn't open a dialog anymore.
Is there some command line I can run to give the permission ? Otherwise I'll just delete the whole folder I guess

**Comment by vashpan** [comment] 2023-11-02 12:39
First, try to give some details about your software: OS version, app version

Hmm, not sure what happens try to:

- Delete the app
- Delete app sandbox folder `~/Library/Containers/com.oneminutegames.XcodeCleaner`

And maybe try again?

**Comment by willxy** [comment] 2024-11-12 19:14
Just installed it, and I'm seeing the same thing (well, not the beachball).  Running ventura, 13.6.6.  Installed from app store.  It came up, I clicked the "Give Access" button, it gave a file selection dialog and I clicked "open".  But it still shows the "Give Access" button, and now when I click on it, nothing happens.  Checked system preferences privacy & security "Files and Folders", but it's not listed there.  Also not listed in "Full Disk Access"; tried adding it manually there, and that didn't make any difference.

**Comment by tranquocminh1112** [comment] 2024-12-20 03:55
I have the same issue, I'm using Sequoia.

> Just installed it, and I'm seeing the same thing (well, not the beachball). Running ventura, 13.6.6. Installed from app store. It came up, I clicked the "Give Access" button, it gave a file selection dialog and I clicked "open". But it still shows the "Give Access" button, and now when I click on it, nothing happens. Checked system preferences privacy & security "Files and Folders", but it's not listed there. Also not listed in "Full Disk Access"; tried adding it manually there, and that didn't make any difference.

**Comment by soychicka** [comment] 2026-03-11 01:05
I just saw the same issue, and I had just deleted CoreSimulator manually.

Restored the directory, and it loaded immediately.

I'm guessing edge conditions are:

1. start to clean up junk yourself
2. realize it's too much to deal with
3. find DevCleaner, install
4. spend too much time looking for a plist or cached file blocking full init.

aaaah, the irony.

thanks @PreludeAndFugue !
